# Generated by Django 3.1.7 on 2022-01-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Shopping_Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemdetails',
            name='long_desc',
            field=models.CharField(blank=True, db_column='LONG_DESC', max_length=3000, null=True, verbose_name='Product Long desc'),
        ),
        migrations.AddField(
            model_name='scitem',
            name='long_desc',
            field=models.CharField(blank=True, db_column='LONG_DESC', max_length=3000, null=True, verbose_name='Product Long desc'),
        ),
    ]
