# Generated by Django 3.1.7 on 2022-02-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Shopping_Cart', '0002_auto_20220118_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='scitem',
            name='accounting_change_flag',
            field=models.BooleanField(blank=True, db_column='ACCOUNTING_CHANGE_FLAG', default=False, null=True, verbose_name='Accounting change flag'),
        ),
        migrations.AddField(
            model_name='scitem',
            name='address_change_flag',
            field=models.BooleanField(blank=True, db_column='ADDRESS_CHANGE_FLAG', default=False, null=True, verbose_name='Address change flag'),
        ),
        migrations.AddField(
            model_name='scitem',
            name='attachment_existence_flag',
            field=models.BooleanField(blank=True, db_column='ATTACHMENT_EXISTENCE_FLAG', default=False, null=True, verbose_name='Attachment existence flag'),
        ),
        migrations.AddField(
            model_name='scitem',
            name='internal_note_existence_flag',
            field=models.BooleanField(blank=True, db_column='INTERNAL_NOTE_EXISTENCE_FLAG', default=False, null=True, verbose_name='Internal note existence flag'),
        ),
        migrations.AddField(
            model_name='scitem',
            name='supplier_note_existence_flag',
            field=models.BooleanField(blank=True, db_column='SUPPLIER_NOTE_EXISTENCE_FLAG', default=False, null=True, verbose_name='Supplier note existence flag'),
        ),
    ]
