# Generated by Django 3.1.7 on 2021-12-27 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eProc_Chat', '0001_initial'),
        ('eProc_Configuration', '0001_initial'),
        ('eProc_Shopping_Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipants',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='chatparticipants',
            name='language_id',
            field=models.ForeignKey(db_column='LANGUAGE_ID', max_length=5, null=True, on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.languages'),
        ),
        migrations.AddField(
            model_name='chatcontent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients'),
        ),
        migrations.AddField(
            model_name='chatcontent',
            name='sc_header_guid',
            field=models.ForeignKey(blank=True, db_column='SC_HEADER_GUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Shopping_Cart.scheader'),
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipants',
            unique_together={('room_no', 'client', 'username', 'chat_type')},
        ),
    ]
