# Generated by Django 3.1.7 on 2022-01-18 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0002_auto_20211227_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetextdetails',
            name='currency_id',
            field=models.ForeignKey(db_column='CURRENCY_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eProc_Configuration.currency'),
        ),
    ]
