# Generated by Django 3.1.7 on 2022-04-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0003_freetextdetails_currency_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='determineglaccount',
            name='gl_acc_num',
            field=models.CharField(db_column='GL_ACC_NUM', max_length=10, null=True),
        ),
    ]
